spring:
  profiles:
    active: ${SPRING_PROFILE:with-mocks}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_by.default_null_ordering: last
        format_sql: true
        default_schema: public
    open-in-view: false
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:userservice}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: embedded